<a href="https://colab.research.google.com/github/sudeepsikha/sudeepsikha/blob/main/regression%2C_multi_regression%2C_polynomial_regression_sunday07.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:

import numpy as np

In [ ]:
from sklearn.linear_model import LinearRegression

In [ ]:
x=np.array([2010, 2012, 2014, 2016, 2018, 2020]).reshape((-1,1))
y=np.array([50, 60, 75, 100, 110, 125])

In [ ]:
x

array([[2010],
       [2012],
       [2014],
       [2016],
       [2018],
       [2020]])

x.shape

In [ ]:
x.shape

(6, 1)

In [ ]:
y=np.array([50, 60, 75, 100, 110, 125])

In [ ]:
model= LinearRegression()

In [ ]:
model.fit(x, y)


LinearRegression()

In [ ]:
x_new = np.array([2022]).reshape(-1,1)

In [ ]:
y_pred = model.predict(x)

In [ ]:
y_pred

array([ 47.38095238,  63.0952381 ,  78.80952381,  94.52380952,
       110.23809524, 125.95238095])

In [ ]:
x_new = np.array([2022]).reshape(-1,1)

In [ ]:
y_pred = model.predict(x_new)

In [ ]:
y_pred

array([141.66666667])

In [ ]:
x_new = np.array([2022, 2025, 2030]).reshape(-1,1)

In [ ]:
y_pred = model.predict(x_new)

In [ ]:
y_pred

array([141.66666667, 165.23809524, 204.52380952])

In [ ]:
r_sq = model.score(x,y)
print(r_sq)

0.9858772406300933


In [ ]:
model.intercept_

-15745.476190476189

In [ ]:
model.coef_

array([7.85714286])

In [ ]:
#multi Linear Regression

In [ ]:
import numpy as np

In [ ]:
from sklearn.linear_model import LinearRegression

In [ ]:
x = np.array ( [ [0, 1], [5, 1], [15, 2], [25, 5],
[35, 11], [45, 15], [55, 34], [60, 35] ] )

In [ ]:
x

array([[ 0,  1],
       [ 5,  1],
       [15,  2],
       [25,  5],
       [35, 11],
       [45, 15],
       [55, 34],
       [60, 35]])

In [ ]:
x.shape

(8, 2)

In [ ]:
y = np.array( [4, 5, 20, 14, 32, 22, 38, 43] )

In [ ]:
y

array([ 4,  5, 20, 14, 32, 22, 38, 43])

In [ ]:
model = LinearRegression()

model.fit(x, y)

LinearRegression()

In [ ]:
y_pred = model.predict(x)

In [ ]:
y_pred

array([ 5.77760476,  8.012953  , 12.73867497, 17.9744479 , 23.97529728,
       29.4660957 , 38.78227633, 41.27265006])

In [ ]:
model.score(x,y)

0.8615939258756776

In [ ]:
model.intercept_

5.52257927519819

In [ ]:
model.coef_

array([0.44706965, 0.25502548])

In [ ]:
#Polynominal regression

In [ ]:
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures


In [ ]:
x = np.array([5, 15, 25, 35, 45, 55]).reshape((-1, 1))
y = np.array([15, 11, 2, 8, 25, 32])


In [ ]:
x_poly = PolynomialFeatures(degree=3)
x_poly.fit(x)
x_new = x_poly.transform(x)


In [ ]:
x

array([[ 5],
       [15],
       [25],
       [35],
       [45],
       [55]])

In [ ]:
x.shape

(6, 1)

In [ ]:
model = LinearRegression()
model.fit(x_new, y)


LinearRegression()

In [ ]:
y_pred = model.predict(x_new)

In [ ]:
y_pred

array([16.49206349,  6.46825397,  5.20634921, 10.65079365, 20.74603175,
       33.43650794])