<a href="https://colab.research.google.com/github/sudeepsikha/sudeepsikha/blob/main/TITANIC_MACHINE_LEARNING_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df=pd.read_csv('Titanic-Dataset.csv')

In [ ]:
df

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


In [ ]:
cols=['Name','Ticket','Cabin']

In [ ]:
df=df.drop(cols, axis=1)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Sex          891 non-null    object 
 4   Age          714 non-null    float64
 5   SibSp        891 non-null    int64  
 6   Parch        891 non-null    int64  
 7   Fare         891 non-null    float64
 8   Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(2)
memory usage: 62.8+ KB


In [ ]:
#drop rows with missing values
#Nans

In [ ]:
# we are wasting data. Machine learning models need data to train and perform well.
#preserve the data and make use of it as much as we can

In [ ]:
#create dummies
dummies=[]
cols=['Pclass','Sex','Embarked']
for col in cols:
    dummies.append(pd.get_dummies(df[col]))


In [ ]:
titanic_dummies=pd.concat(dummies, axis=1)

In [ ]:
#1,2,3 represent passenger class
#concatenate to the original data frame. column wise:
pd.concat((df,titanic_dummies),axis=1)

PassengerId  Survived  Pclass     Sex   Age  SibSp  Parch     Fare  \
0              1         0       3    male  22.0      1      0   7.2500   
1              2         1       1  female  38.0      1      0  71.2833   
2              3         1       3  female  26.0      0      0   7.9250   
3              4         1       1  female  35.0      1      0  53.1000   
4              5         0       3    male  35.0      0      0   8.0500   
..           ...       ...     ...     ...   ...    ...    ...      ...   
886          887         0       2    male  27.0      0      0  13.0000   
887          888         1       1  female  19.0      0      0  30.0000   
888          889         0       3  female   NaN      1      2  23.4500   
889          890         1       1    male  26.0      0      0  30.0000   
890          891         0       3    male  32.0      0      0   7.7500   

    Embarked      1      2      3  female   male      C      Q      S  
0          S  False  False   True   False   True  False  False   True  
1          C   True  False  False    True  False   True  False  False  
2          S  False  False   True    True  False  False  False   True  
3          S   True  False  False    True  False  False  False   True  
4          S  False  False   True   False   True  False  False   True  
..       ...    ...    ...    ...     ...    ...    ...    ...    ...  
886        S  False   True  False   False   True  False  False   True  
887        S   True  False  False    True  False  False  False   True  
888        S  False  False   True    True  False  False  False   True  
889        C   True  False  False   False   True   True  False  False  
890        Q  False  False   True   False   True  False   True  False  

[891 rows x 17 columns]

In [ ]:
df=df.drop(['Pclass','Sex','Embarked'], axis=1)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Age          714 non-null    float64
 3   SibSp        891 non-null    int64  
 4   Parch        891 non-null    int64  
 5   Fare         891 non-null    float64
dtypes: float64(2), int64(4)
memory usage: 41.9 KB


In [ ]:
# how to take care of missing values
#Age
#interpolate() function that will replace the missing Nans to interpolate values

In [ ]:
df['Age']=df['Age'].interpolate()

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Age          891 non-null    float64
 3   SibSp        891 non-null    int64  
 4   Parch        891 non-null    int64  
 5   Fare         891 non-null    float64
dtypes: float64(2), int64(4)
memory usage: 41.9 KB


In [ ]:
#Convert the data frame to Numpy
#its time to prepare the data for machine leaning models

In [ ]:
#scikit-learn and numpy come into play

In [ ]:
#X=Input set with 14 attributes
#y=small y output Survived
#Now we convert our data frame from pandas to Numpy and we assign input and output.

In [ ]:
X=df.values

In [ ]:
y=df['Survived'].values

In [ ]:
y

array([0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1,
       1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0,
       1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1,

In [ ]:
X

array([[  1.    ,   0.    ,  22.    ,   1.    ,   0.    ,   7.25  ],
       [  2.    ,   1.    ,  38.    ,   1.    ,   0.    ,  71.2833],
       [  3.    ,   1.    ,  26.    ,   0.    ,   0.    ,   7.925 ],
       ...,
       [889.    ,   0.    ,  22.5   ,   1.    ,   2.    ,  23.45  ],
       [890.    ,   1.    ,  26.    ,   0.    ,   0.    ,  30.    ],
       [891.    ,   0.    ,  32.    ,   0.    ,   0.    ,   7.75  ]])

In [ ]:
#X still has survived values in it, which should not be there
#So we drop in the Numpy column, which is the first column

In [ ]:
X=np.delete(X,1,axis=1)

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
#Divide the dataset into training and testing the dataset
X

array([[  1.    ,  22.    ,   1.    ,   0.    ,   7.25  ],
       [  2.    ,  38.    ,   1.    ,   0.    ,  71.2833],
       [  3.    ,  26.    ,   0.    ,   0.    ,   7.925 ],
       ...,
       [889.    ,  22.5   ,   1.    ,   2.    ,  23.45  ],
       [890.    ,  26.    ,   0.    ,   0.    ,  30.    ],
       [891.    ,  32.    ,   0.    ,   0.    ,   7.75  ]])